// <auto-generated />
using Churras.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Churras.Repository.Migrations
{
    [DbContext(typeof(ChurrasContext))]
    [Migration("20180123195119_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Churras.Domain.Models.Barbecue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("CostWithDrink");

                    b.Property<decimal>("CostWithoutDrink");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Barbecues");
                });

            modelBuilder.Entity("Churras.Domain.Models.Participant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BarbecueId");

                    b.Property<decimal>("Dough");

                    b.Property<bool>("IsGoingToDrink");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BarbecueId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("Churras.Domain.Models.Participant", b =>
                {
                    b.HasOne("Churras.Domain.Models.Barbecue", "Barbecue")
                        .WithMany("Participants")
                        .HasForeignKey("BarbecueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
